name: Forge-Sovereign-Dylib
on: [push]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Compiling ARM64 Dylib
        run: |
          # أمر الصهر السيادي باستخدام مترجم Xcode الرسمي (نخاع آبل)
          clang -dynamiclib -arch arm64 main.cpp -o wsam_soldier.dylib -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Wsam-Sovereign-Dylib-Artifact
          path: wsam_soldier.dylib
